version: '3.9'

name: runnetic-ws-user

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres-ws-user
    networks:
      - runnetic-ws-user
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user

  ws-user:
    image: 'runnetic/ws-user:latest'
    build:
      context: .
    container_name: ws-user
    depends_on:
      - db
    networks:
      - kafka_network
      - runnetic-ws-user
    ports:
      - "9002:8080"
    environment:
      app.datasource.url: jdbc:postgresql://postgres-ws-user:5432/user
      app.datasource.driver: org.postgresql.Driver
      app.datasource.username: postgres
      app.datasource.password: postgres
      app.jpa.driver: org.hibernate.dialect.PostgreSQLDialect
      app.kafka.bootstrap-servers: kafka:9092
      app.schema.registry.url: http://schema-registry:8081
      app.server.port: 8080
      app.logging.level: info
      app.swagger.ui.enabled: true

networks:
  kafka_network:
    external: true
  runnetic-ws-user:
    name: runnetic-ws-user