version: '3.9'

name: runnetic-ws-analytics

services:
  ws-analytics:
    image: 'runnetic/ws-analytics:latest'
    build:
      context: .
    container_name: ws-analytics
    networks:
      - elastic_network
      - runnetic-ws-analytics
      - kafka_network
    ports:
      - "9003:8080"
    environment:
      app.server.port: 8080
      app.kafka.bootstrap-servers: kafka:9092
      app.schema.registry.url: http://schema-registry:8081
      app.elasticsearch.uris: http://elasticsearch:9200
      app.elasticsearch.username: elastic
      app.elasticsearch.password: changeme

networks:
  elastic_network:
    external: true
  kafka_network:
    external: true
  runnetic-ws-analytics:
    name: runnetic-ws-analytics