# ===============================================================
# Configuration file
# ===============================================================

server.port: 8080
spring:
  # GENERAL
  application:
    name: kafka-spring-boot-ws-order
  # DATASOURCE
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  # KAFKA
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: groupId
    producer:
      bootstrap-servers: localhost:29092

# ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: '*'

# SWAGGER UI
springdoc:
  swagger-ui:
    enabled: true
    path: /
