openapi: 3.0.1

info:
  title: KSB Order API
  description: KSB Order API - API Swagger documentation
  version: 1.0.0-SNAPSHOT

servers:
- url: http://localhost:8080
  description: Localhost server url

tags:
- name: Order
  description: Order operations

paths:
  /orders:
    post:
      tags:
      - Order
      summary: Create order
      description: Create a new order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestOrderApiDto'
      responses:
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseOrderApiDto'

components:
  schemas:
    ErrorResponse:
      type: object
      description: Response in case of error
      properties:
        code:
          type: string
          description: Error code
          example: [BR1]
        description:
          type: string
          description: Error description
          example: Field 'name' cannot be null

    RequestOrderApiDto:
      required:
      - userUuid
      - products
      type: object
      description: Request body for placing an order
      properties:
        userUuid:
          type: string
          description: The ID of the user placing the order.
          example: e58ed763-928c-4155-bee9-fdbaaadc15f3
          format: uuid
        products:
          type: array
          description: List of products in the order. Each product must specify the product ID and quantity required.
          items:
            $ref: '#/components/schemas/ProductApiDto'

    ProductApiDto:
      type: object
      description: Represents a product to be purchased
      required:
        - productUuid
        - quantity
        - price
      properties:
        productUuid:
          type: string
          format: uuid
          description: Required product identifier
          example: e58ed763-928c-4155-bee9-fdbaaadc15f3
        quantity:
          type: integer
          description: Quantity of product desired
          example: 2
        price:
          type: number
          format: double
          description: Product price
          example: 100.00

    ResponseOrderApiDto:
      type: object
      properties:
        orderUuid:
          type: string
          description: Order number
          example: e58ed763-928c-4155-bee9-fdbaaadc15f3
        status:
          type: string
          description: Order status
          example: created
        totalPrice:
          type: number
          description: Total price of order
          format: double
          example: 149.99
        orderDate:
          type: string
          format: date-time
          description: Order date and time
          example: 2025-01-09T10:30:00Z
